# These are supported funding model platforms

github: Revxrsal # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
ko_fi: https://ko-fi.com/revxrsal # Replace with a single Ko-fi username
